#!/usr/bin/env bash
# Writes TimeTracker/Services/SyncSecrets.swift (gitignored) from the environment.
# The repo is public, so the sync API URL and token must never be committed.
#
#   SYNC_API_BASE_URL=https://timetracker-sync.<sub>.workers.dev \
#   SYNC_API_TOKEN=<token> scripts/write-sync-secrets.sh
#
# Locally the values live in sync-api/.dev.vars (also gitignored); CI reads GitHub secrets.
set -euo pipefail

: "${SYNC_API_BASE_URL:?SYNC_API_BASE_URL is required}"
: "${SYNC_API_TOKEN:?SYNC_API_TOKEN is required}"

out="$(cd "$(dirname "$0")/.." && pwd)/TimeTracker/Services/SyncSecrets.swift"
cat > "$out" <<SWIFT
// Generated by scripts/write-sync-secrets.sh. Do not commit (gitignored).
enum SyncSecrets {
    static let baseURL = "${SYNC_API_BASE_URL}"
    static let apiToken = "${SYNC_API_TOKEN}"
}
SWIFT
echo "Wrote $out"
